### ISSUE TITLE
re sizeable world

### ISSUE THREAD

**Issue by Thanduriel** [Thanduriel/Fade#2]
make the world size / camera view adjustable without changing the window size
- what are sensible scale values
- should the range of possible values change depended on the window size

**Comment by jokiel** [comment]
-  I guess the given scales are suitable for two, possibly three players at full HD, but that depends a bit on how we adjust gameplay
- we could pass a scaling factor to all sprites and shaders that depends on the window width to get more or less identical scales for all resolutions, yet another factor would control the allowed world sizes: small (similar to the current scales, i.e. 1.0), medium (3-4 players, e.g. 1.5) and big (4 and more players, e.g. 2.0)
